[project]
name = "ta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "numpy>=2.3.4",
    "ta-lib>=0.6.8",
]
